// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
module.exports = function(app){
  <% if (parsedSwagger) {
       if (parsedSwagger.basepath) { -%>
    const basepath = "<%- parsedSwagger.basepath %>";
  <%   } else { -%>
    const basepath = '';
  <%   }
     }
     if( genSwagger ){ %>
    require('./swagger')(app);
  <% } 
     if ( !parsedSwagger ) {%>
    require('./public')(app);
  <% }
     if(typeof spec === 'undefined' || spec.applicationType !== 'BLANK'){ %>
    require('./health')(app);
  <% }
     if (parsedSwagger) {
       Object.keys(parsedSwagger.resources).forEach(function(resource) { -%>
    require('./<%- resource %>')(app, basepath);
  <%   });
     } -%>
  };  